### ISSUE TITLE
Please remove unnecessary files

### ISSUE THREAD

**Issue by pcav** [Diuke/GeoPriv#8]
.pyc etc.
They are generated automatically during installation.
Thanks.

**Comment by Diuke** [comment]
I think I deleted all unnecessary files.
Let me know if there is another.

**Comment by pcav** [comment]
Still here: https://github.com/Diuke/GeoPriv/tree/master/__pycache__
Cheers.

**Comment by Diuke** [comment]
Done, thank you very much

**Comment by pcav** [comment]
Thanks.
